services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Pehapkari\Blog\:
        resource: '../src'
        exclude:
            - '../src/ValueObject/*'
            - '../src/Posts/Year2016/*/Event/*'
            - '../src/Posts/Year2017/NetteConfigObjects/*'
            - '../src/Posts/Year2018/Cart/Domain/*'

    # for rendering markdown posts
    ParsedownExtra:
        class: 'ParsedownExtra'
