# template only routes → template
contact:
    path: 'kontakt'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'homepage/contact.twig'

for_speakers:
    path: 'for-speakers'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'meetup/for_speakers.twig'
