imports:
    - { resource: '_data/*.yaml' }

parameters:
    locale: 'en' # for easy admin bundle
    image_uploads: "/uploads/images/"
    route_usage_exclude_routes:
        - "rss"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Pehapkari\:
        resource: '../src/'
        exclude:
            - '../src/PehapkariKernel.php'
            - '../src/Doctrine/Query/*'
            - '../src/ValueObject/*'
            - '../src/Exception/*'

    Defr\Ares: ~
    GuzzleHttp\Client: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    Symplify\PackageBuilder\Reflection\PrivatesAccessor: ~
    Symplify\SmartFileSystem\Finder\FinderSanitizer: ~

    # latte filters in twig
    Latte\Runtime\FilterExecutor: ~

    # email validator
    Egulias\EmailValidator\EmailValidator: ~
