parameters:
    authors:
        1:
            name: "Tomáš Votruba"
            photo: "https://avatars2.githubusercontent.com/u/924196?s=460&v=4"
        2:
            name: "Pavel Rozehnal"
        3:
            name: "Michal Lulčo"
        4:
            name: "Petr Hejna"
        5:
            name: "Jáchym Toušek"
            photo: "https://avatars1.githubusercontent.com/u/539462?s=460&v=4"
        6:
            name: "Tomáš Fejfar"
        7:
            name: "Tom Klíma"
        8:
            name: "Petr Vácha"
        9:
            name: "Martina Hynková"
        10:
            name: "Petr Olišar"
        11:
            name: "Tomáš Pilař"
            photo: "https://avatars0.githubusercontent.com/u/8326937?s=460&v=4"
        12:
            name: "Tomáš Jacík"
            photo: "https://avatars2.githubusercontent.com/u/1284781?s=460&v=4"
        13:
            name: "Martin Zlámal"
        14:
            name: "Ivan Kvasnica"
        15:
            name: "Matěj Račinský"
            photo: "https://media-exp1.licdn.com/dms/image/C5603AQF16PZis0gOGA/profile-displayphoto-shrink_200_200/0?e=1584576000&v=beta&t=yuvMpXCDRYhkasPS-XzUlFwuKeGc_Pr3828aeeB8Y0w"
        16:
            name: "Jaroslav Hranička"
        17:
            name: "Michael Moravec"
        18:
            name: "Michal Špaček"
        19:
            name: "Václav Makeš"
        20:
            name: "Petr Jirásek"
        21:
            name: "Honza Černý"
            photo: "https://avatars0.githubusercontent.com/u/42802?s=460&v=4"
        22:
            name: "Lukáš Vraný"
        23:
            name: "Filip Procházka"
        24:
            name: "Honza Kuchař"
        25:
            name: "David Matějka"
        26:
            name: "Milan Felix Šulc"
        27:
            name: "Martin Knor"
        28:
            name: "Petr 'PePa' Pavel"
        29:
            name: "Svaťa Šimara"
            photo: "https://avatars2.githubusercontent.com/u/1669982?s=460&v=4"
        30:
            name: "Michal Katuščák"
            photo: "https://avatars0.githubusercontent.com/u/1405383?s=460&v=4"
        31:
            name: "Roman Veselý"
        32:
            name: "Jan Mikeš"
        33:
            name: "Eduard Barnáš"
            photo: "https://avatars0.githubusercontent.com/u/25415042?s=460&v=4"
        34:
            name: "Vladimír Macháček"
        35:
            name: "Łukasz Chruściel"
        36:
            name: "Richard Koza"
