#!/bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

# Permissions hack because setfacl does not work on Mac and Windows
chmod 777 -R var

composer install --prefer-dist --no-progress --no-suggest --no-interaction -o

## bin/console assets:install ## is run automatically - check composer.json scripts:auto-scripts

# Run (original) Docker command
exec "$@"
