services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pehapkari\Youtube\:
        resource: '../src'
        exclude:
            '../src/ValueObject/*'

    Symplify\PackageBuilder\Strings\StringFormatConverter: null
    Symfony\Component\Cache\Adapter\FilesystemAdapter: null

parameters:
    youtube_api_key: '%env(YOUTUBE_API_KEY)%'
