version: "3.7"
services:
    web:
        image: pehapkari_cz
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/pehapkari.cz:cached
        tmpfs:
            - /var/www/pehapkari.cz/var/cache

    yarn-watch:
        image: node:14-alpine
        restart: unless-stopped
        working_dir: /var/www/pehapkari.cz
        volumes:
            - .:/var/www/pehapkari.cz:delegated
        entrypoint: [ "" ]
        command: "ash -c 'yarn install && yarn run watch'"
